# Generated by Django 5.2.8 on 2025-11-12 14:24

import django.core.files.storage
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrochureDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(blank=True, choices=[('Altura', 'Altura'), ('Beachgate by Address', 'Beachgate by Address'), ('Damac Bay by Cavalli', 'Damac Bay by Cavalli'), ('DLF West Park', 'DLF West Park'), ('Godrej Vistas', 'Godrej Vistas'), ('Lumina Grand', 'Lumina Grand'), ('Sobha Crest', 'Sobha Crest'), ('Sobha Waves', 'Sobha Waves')], max_length=64)),
                ('original_name', models.CharField(max_length=255)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='/media/ads/Data/proplens_ai_rag/media/brochures'), upload_to='')),
                ('checksum', models.CharField(editable=False, max_length=64)),
                ('content_type', models.CharField(blank=True, max_length=128)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('last_indexed_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_brochures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.CreateModel(
            name='DocumentIngestionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=32)),
                ('detail', models.TextField(blank=True)),
                ('chunks_indexed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_logs', to='agents.brochuredocument')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
