# Generated by Django 5.2.8 on 2025-11-12 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crm_id', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(blank=True, max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('project_enquired', models.CharField(choices=[('Altura', 'Altura'), ('Beachgate by Address', 'Beachgate by Address'), ('Damac Bay by Cavalli', 'Damac Bay by Cavalli'), ('DLF West Park', 'DLF West Park'), ('Godrej Vistas', 'Godrej Vistas'), ('Lumina Grand', 'Lumina Grand'), ('Sobha Crest', 'Sobha Crest'), ('Sobha Waves', 'Sobha Waves')], max_length=64)),
                ('unit_type', models.CharField(choices=[('studio', 'Studio'), ('1 bed', '1 Bed'), ('2 bed', '2 Bed'), ('2 bed w study', '2 Bed with Study'), ('3 bed', '3 Bed'), ('4 bed', '4 Bed'), ('duplex', 'Duplex'), ('penthouse', 'Penthouse')], max_length=32)),
                ('status', models.CharField(choices=[('not_connected', 'Not Connected'), ('connected', 'Connected'), ('visit_scheduled', 'Visit Scheduled'), ('visit_done_not_purchased', 'Visit Done Not Purchased'), ('purchased', 'Purchased'), ('not_interested', 'Not Interested')], default='not_connected', max_length=64)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('family_size', models.PositiveIntegerField(blank=True, null=True)),
                ('location_preference', models.CharField(blank=True, max_length=128)),
                ('purchase_motive', models.CharField(blank=True, max_length=256)),
                ('financing_readiness', models.CharField(blank=True, max_length=128)),
                ('profile_metadata', models.JSONField(blank=True, default=dict)),
                ('last_conversation_date', models.DateField(blank=True, null=True)),
                ('last_conversation_summary', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, help_text='Owner within the sales team.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
    ]
